import 'server-only';

import { promises as fs } from 'node:fs';
import path from 'node:path';

import type { Dataset } from './types';

const DATA_PATH = path.join(process.cwd(), 'data', 'startups.json');

const EMPTY: Dataset = { version: 1, generatedAt: null, caveats: [], companies: [] };

/**
 * Tolerant on purpose: the file is regenerated by scripts/ingest_yc.py, and a
 * missing or half-written file should render an empty map, not a 500.
 */
export async function loadDataset(): Promise<Dataset> {
  try {
    const parsed = JSON.parse(await fs.readFile(DATA_PATH, 'utf8')) as Partial<Dataset>;
    if (!Array.isArray(parsed.companies)) {
      console.warn('[data] startups.json has no companies array');
      return EMPTY;
    }
    return {
      version: parsed.version ?? 1,
      generatedAt: parsed.generatedAt ?? null,
      caveats: parsed.caveats ?? [],
      companies: parsed.companies,
    };
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      console.warn('[data] could not read startups.json:', error);
    }
    return EMPTY;
  }
}
